### ISSUE TITLE
No option to select Go as the environment for debugging

### ISSUE THREAD

**Issue by ptasker** [vscode-kubernetes-tools/vscode-kubernetes-tools#1082] opened 2022-05-30 17:31 UTC
Hi there 👋, based on [this doc](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/debug-on-kubernetes.md#8-go-debugging) it appears that the `Debug (Attach)` configuration supports Go, but I'm not able to select Go as the environment. Is there anything required to enable Go as an environment for debugging?

See screencast:

![k8s-debug](https://user-images.githubusercontent.com/535651/171038671-cc32f24a-c790-4344-9799-5fe1f5aa4f22.gif)

**Comment by lstocchi** [comment] 2022-08-26 13:52
Hi @ptasker, sorry for the late response. Could you please tell me which is the plugin version installed? Just tried quickly and i can see the go option. Do you have any app we can use to reproduce it?

**Comment by eggyhead** [comment] 2022-10-19 20:30
:wave: I'm having the same issue on version `v1.3.10`

**Comment by lstocchi** [comment] 2023-06-06 07:59
Closing it as i was not able to reproduce. Most probably you miss `dlv` from the command that launched the process but i cannot know without more infos. Feel free to reopen it if you didn't solve it in the meantime. 

There was actually another issue in the current release that was fixed by https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1185 . In the next days we're releasing the new version so you can try. Thanks!!

**Closed by lstocchi** 2023-06-06 07:59 UTC

**Comment by pWoLiAn** [comment] 2023-06-08 17:48
I am able to reproduce the issue on v1.3.12. let me know what extra info is needed

**Comment by lstocchi** [comment] 2023-06-09 07:43
@pWoLiAn you should add it in your Dockerfile to being able to debug your container.
Let's say you have 
```
# Compile stage
FROM golang:1.17 AS build-env

ADD . /dockerdev
WORKDIR /dockerdev
RUN go build -o /server
# Final stage
FROM debian:buster
EXPOSE 8000 
WORKDIR /
COPY --from=build-env /server /
CMD ["/server"]
```

you should add dlv so it becomes
```
# Compile stage
FROM golang:1.17 AS build-env

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

ADD . /dockerdev
WORKDIR /dockerdev

RUN go build -gcflags="all=-N -l" -o /server

# Final stage
FROM debian:buster

EXPOSE 8000 40000

WORKDIR /
COPY --from=build-env /go/bin/dlv /
COPY --from=build-env /server /

CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/server"]
```

You can also find many tutorial about dlv online. 
Or if you can share your app I can try debugging it.

**Comment by pWoLiAn** [comment] 2023-06-09 16:25
@lstocchi Thanks for the detailed explanation. I wasn't aware of the proper procedure since the documentation was pretty basic. It would be very helpful for folks like me, who are trying the feature out for the first time, if you could add any credible sources or your own complete steps to the documentation.

Coming back to the issue, I noticed that few of the other pods were still listing go even though they weren't running any dlv instances. In fact, I noticed this issue only on one particular pod and the only difference I noticed was that this one was using a base ubuntu 18.04 image and the others an alpine image.
