### ISSUE TITLE
No remote extension installed to resolve dev-k8s. After updating to vscode 1.80

### ISSUE THREAD

**Issue by RozmarinUS** [vscode-kubernetes-tools/vscode-kubernetes-tools#1199] opened 2023-07-08 03:02 UTC
After updating to the latest version, got an error when attaching vscode in the pod

```
ERR No remote extension installed to resolve dev-k8s.: CodeExpectedError: No remote extension installed to resolve dev-k8s.
    at e.$W9b.ob (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19839)
    at async e.$W9b.nb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2609:19105)
    at async e.$W9b.Lb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2610:11242)
    at async e.$W9b.gb (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2609:16869)
```
 
 If rollback the version everything is fine

**Comment by flinz** [comment] 2023-07-10 07:51
Can confirm, vscode 1.80 update broke the ability to attach VSCode to pods. Same error message, where `dev-k8s` is the cluster.

**Comment by bulak** [comment] 2023-07-10 07:57
Exactly the same error: `No remote extension installed to resolve <cluster>` with cluster being our k8 cluster address. All aspects of k8s work outside of VS Code. Other users with version 1.79 can connect to the same environment without any issues. Only users with version 1.80 have this issue.

**Comment by bulak** [comment] 2023-07-10 08:04
Downgrading to below fixed the problem:

```Version: 1.79.2
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:59:55.818Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-46-generic
```

**Comment by daviddale** [comment] 2023-07-26 17:44
Downgraded 1.79 as well and fixed the problem. 
Monitoring this issue due to vscode updates needing to be halted until this is resolved.

**Comment by bulak** [comment] 2023-08-18 09:03
I was wondering if there is any development on this issue? Either on the extension side or on the never versions of VS Code, which might have fixed the issue without a need of patching the extension.. Any input is appreciated.

**Comment by spammads** [comment] 2023-09-09 13:03
I also ran into this. Would appreciate a fix.

**Comment by Tatsinnit** [comment] 2023-11-05 22:20
Hiya, a big thank you for bringing up this matter and engaging in the discussion. We appreciate your contributions, @RozmarinUS, @flinz, @bulak, @daviddale, and @spammads. As I'm composing this message, we're actively investigating the issue, and we'll provide an update once we (either @peterbom or myself) have a clearer understanding of the situation. Once again, your input is greatly valued. Copying @squillace for awareness. ❤️🙏

**Comment by peterbom** [comment] 2023-11-06 00:59
Hi @RozmarinUS, @flinz, @bulak, @daviddale, and @spammads:

Just to double-check we're looking at the right thing, we're talking about the "Attach Visual Studio Code" option from the pod context menu, which opens up a new VS Code window in the context of that pod. Is that correct?
<img width="165" alt="image" src="https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/1817696/a94774f4-ed66-4b2e-b25f-efb43f79e359">

As the new window opens, a prompt appears giving the option to 'show log' for the Dev Container, which opens up a terminal in the new window showing various commands relating to the VS Code server being run in the pod using `kubectl exec`. Is that where the error message is appearing, or is there something extra we need to do?

So far, @Tatsinnit and I haven't been able to reproduce the issue. We've tried with VS Code versions 1.80.0 and 1.80.2, as well as the latest and various older versions of the Dev Containers (`ms-vscode-remote.remote-containers`) extension, on both Windows/WSL and Mac.

Would you be able to let us know:
- Is this issue still occurring for you?
- Where are you seeing the error? Is it in the terminal in the newly launched VS Code window?
- Could you share the preceding logs before the error?
- What OS is this happening on?
- What is the VS Code version?
- What is the Kubernetes extension version?
- What is the Dev Containers extension version?

**Comment by RozmarinUS** [comment] 2023-11-06 01:15
Hi! @peterbom
1) yeah is this issue occurred if vs code version more then 1.79.2
2) Yes, when you click on "Attach vissual studio code"
4) Linux Mint 21, Windows 11 same error
5) Just now updated on the latest version 1.84
6) Kubernetes extension version is v1.3.15
7) Dev container extension version is v0.321.0
![2023-11-05-17-11-44](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/assets/28756181/2a7e058e-a0f0-414f-9587-cea2d8be0d0d)

**Comment by peterbom** [comment] 2023-11-06 02:11
Thanks for all the help, @RozmarinUS!

We'll keep an eye on any developments in the [open issue](https://github.com/microsoft/vscode-remote-release/issues/8909) comments.

As you've discovered, and for anyone else looking here, a temporary workaround is to remove the '@' symbol in the cluster context.

**Comment by RozmarinUS** [comment] 2023-12-05 12:36
@FlazeNaive you need to delete "@" from cluster context name, this is  temporary solution 
https://github.com/microsoft/vscode-remote-release/issues/8909

**Comment by FlazeNaive** [comment] 2023-12-05 13:01
> @FlazeNaive you need to delete "@" from cluster context name, this is temporary solution [microsoft/vscode-remote-release#8909](https://github.com/microsoft/vscode-remote-release/issues/8909)

Thanks, this solved this problem, but sadly I am working with the uni's cluster and it cannot find the context after i change the name :(

**Comment by skamansam** [comment] 2023-12-07 19:41
I am having the same issue, but unfortunately, this workaround doesn't work for me. As you can see, I don't have any of that in my config:

> the `[...]` just means the data isn't copied here - it's sensitive, maybe

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [...]
    server: https://192.168.1.234:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: local
current-context: local
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: [...]
    client-key-data: [...]

```

**Comment by Hokwang** [comment] 2023-12-20 04:38
still not fixed in v1.85.1

**Comment by ja-nina** [comment] 2024-02-22 01:11
Any news on this?

**Comment by ja-nina** [comment] 2024-02-22 01:17
@FlazeNaive Some time passed - but for future seekers, comming back to 1.79 works indeed and the fix for seeing "Attach to VS" is uninstalling and reinstalling the remote development extensions:) Hope it helps

**Comment by peterbom** [comment] 2024-03-27 01:59
The related issue is now [fixed](https://github.com/microsoft/vscode-remote-release/issues/8909#issuecomment-2021720905) in the pre-release version (0.351.0) of the Dev Containers extension.

I just tried installing that and it seems to fix this issue too. cc: @Tatsinnit

**Comment by Hokwang** [comment] 2024-03-27 04:40
@peterbom Thanks for your notice, I've tested dev container v0.352.0 (pre-release) with vscode v1.87.2, this bug is fixed.

**Closed** 2024-04-10 08:01 UTC
