### ISSUE TITLE
can't debug pod

### ISSUE THREAD

**Issue by GKilm** [vscode-kubernetes-tools/vscode-kubernetes-tools#1114] opened 2022-10-08 08:19 UTC
when I try the `debug(attach) pod` function ,I have a problem to success.It is shown below.

![16652159176569](https://user-images.githubusercontent.com/28996322/194696976-1c8823a3-6243-4af7-95f1-d5a5c73c809e.png)

By the way,the extension is installed in remote-linux-machine.

**Comment by lstocchi** [comment] 2022-11-04 10:57
Hi @GKilm ,
sorry for the late response, could you please give me some more info to replicate your issue? When do you face this error? After clicking the action? If not, after which step? Do you have your project opened on vscode?
Which vscode version are you using?
I tried but i was not able to replicate it, so any help would be great. Thanks!

**Comment by Tatsinnit** [comment] 2022-11-04 18:40
💡🙏☕️Saw this and thought I will add just as fyi in case this fix #1121  takes care of the issue mentioned.

Although, as @lstocchi kindly pointed out and I am not 100 percent sure because no reproducible steps are there.

Thanks

**Comment by GKilm** [comment] 2022-11-07 08:27
Thanks for your response.
I'm sorry for not providing enough information without knowing what is important.

I'm going to show these steps with a gif.
![debug-by-k8s-tool](https://user-images.githubusercontent.com/28996322/200261580-587060cc-84f3-4b14-a843-835e7b103fd8.gif)

Here is the example project [demo](https://github.com/GKilm/test-debug-for-k8s)

The debug work is leaded by [debug-on-kubernetes.md](https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/debug-on-kubernetes.md)

version information:
```
vscode version : 1.72.2
kubernetes version : v1.3.10
Remote-SSH version : v0.90.1
```
![vscode-verson](https://user-images.githubusercontent.com/28996322/200261508-93ad9b8c-2a30-4f9f-85a8-5254b186aa3f.png)
![k8s-tool-version](https://user-images.githubusercontent.com/28996322/200261520-446e374b-fa27-433f-a3d1-46a3a67f7602.png)

Thank you again for your contribution.If more infomation needed,notice me,please.

**Comment by lstocchi** [comment] 2023-06-06 07:55
Closing as https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/pull/1185 was merged. Please feel free to reopen it if you still face the same issue in the next release. Thanks!!

**Closed by lstocchi** 2023-06-06 07:55 UTC
